import React, { useState } from 'react';
import { 
  BookOpen, 
  Upload, 
  FileText, 
  Download, 
  HelpCircle, 
  CheckCircle2, 
  XCircle, 
  RefreshCw, 
  BrainCircuit, 
  Layers, 
  Calendar, 
  Trash2, 
  ChevronRight, 
  Zap, 
  FileCheck,
  MessageSquareText,
  Bot,
  Sparkles
} from 'lucide-react';
import { StudySuite, Flashcard, QuizQuestion, AssignmentItem } from '../../types';
import { exportTextToPDF } from '../../lib/pdfExport';
import { SectionUsageBanner } from '../common/SectionUsageBanner';
import { AIChatView } from '../chat/AIChatView';
import { AssignmentSolverView } from '../assignment/AssignmentSolverView';

interface StudyHubViewProps {
  studySuites: StudySuite[];
  onSaveSuite: (suite: StudySuite) => void;
  onDeleteSuite: (id: string) => void;
  assignments?: AssignmentItem[];
  onAddAssignment?: (assignment: AssignmentItem) => void;
  initialMode?: 'synthesizer' | 'chat' | 'assignment';
}

export const StudyHubView: React.FC<StudyHubViewProps> = ({
  studySuites,
  onSaveSuite,
  onDeleteSuite,
  assignments = [],
  onAddAssignment = () => {},
  initialMode = 'synthesizer',
}) => {
  const [mainMode, setMainMode] = useState<'synthesizer' | 'chat' | 'assignment'>(initialMode);

  const [selectedSuite, setSelectedSuite] = useState<StudySuite | null>(
    studySuites.length > 0 ? studySuites[0] : null
  );

  const [activeTab, setActiveTab] = useState<
    'notes' | 'flashcards' | 'quiz' | 'mindmap' | 'formulas' | 'viva' | 'revision'
  >('notes');

  // Uploader state
  const [showUploader, setShowUploader] = useState(studySuites.length === 0);
  const [title, setTitle] = useState('');
  const [subject, setSubject] = useState('Data Structures');
  const [contentText, setContentText] = useState('');
  const [loading, setLoading] = useState(false);

  // Flashcard state
  const [currentFCIndex, setCurrentFCIndex] = useState(0);
  const [fcFlipped, setFcFlipped] = useState(false);

  // Quiz state
  const [quizAnswers, setQuizAnswers] = useState<Record<string, number>>({});
  const [quizSubmitted, setQuizSubmitted] = useState(false);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const res = await fetch('/api/ai/study-hub', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: title || 'Chapter Lecture Notes',
          subject: subject || 'General Science',
          contentText: contentText || 'Lecture coverage on core principles and problem solving.',
        }),
      });

      const data = await res.json();

      const newSuite: StudySuite = {
        id: 'suite_' + Date.now(),
        userId: 'default',
        title: title || 'Class Notes & Exam Prep',
        subject: subject || 'Computer Science',
        summary: data.summary || 'Summary generated by AI.',
        fullNotes: data.fullNotes || 'Full notes generated.',
        importantQuestions: data.importantQuestions || [],
        flashcards: data.flashcards || [],
        quiz: data.quiz || [],
        mindmap: data.mindmap || { id: 'root', label: title, children: [] },
        formulas: data.formulas || [],
        vivaQuestions: data.vivaQuestions || [],
        revisionPlan: data.revisionPlan || [],
        createdAt: new Date().toISOString(),
      };

      onSaveSuite(newSuite);
      setSelectedSuite(newSuite);
      setShowUploader(false);
      setTitle('');
      setContentText('');
    } catch (err) {
      console.error('Failed to generate study suite:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleExportPDF = () => {
    if (!selectedSuite) return;
    const exportContent = `SUBJECT: ${selectedSuite.subject}\nTITLE: ${selectedSuite.title}\n\nSUMMARY:\n${selectedSuite.summary}\n\nNOTES:\n${selectedSuite.fullNotes}`;
    exportTextToPDF(selectedSuite.title, exportContent, `${selectedSuite.title.replace(/\s+/g, '_')}_Notes.pdf`);
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      {/* Section Usage Banner */}
      <SectionUsageBanner
        title="AI Study Hub, Chat Assistant & Assignment Solver"
        subtitle="Unified Workspace: Note Synthesizer, Flashcards, 24/7 AI Tutor & Step-by-Step Problem Solver"
        purpose="This single unified workspace combines automated lecture synthesis, an autonomous AI Academic Tutor, and an AI Assignment Solver. Convert raw textbooks & syllabus notes into flashcards and quizzes, chat with the AI Tutor for step-by-step proofs & code debugging, or solve complex homework problem sets with textbook references."
        keyFeatures={[
          '24/7 AI Academic Chat Assistant & Reasoning Engine',
          'Automated Lecture Note & Summary Synthesis',
          'AI Step-by-Step Assignment & Proof Solver',
          'Active Recall Flashcards & Practice Quizzes',
          'Formula Cheat Sheets & Mindmap Breakdown',
          'Export Complete Study Suites & Solutions to PDF'
        ]}
        icon={<BookOpen className="w-6 h-6 text-white" />}
        badge="Unified Study, Chat & Solver OS"
      />

      {/* Top Mode Selector Bar (Unified Section) */}
      <div className="flex items-center gap-2 bg-slate-100/90 p-2 rounded-2xl border border-slate-200/80 shadow-3d-sm w-fit flex-wrap">
        <button
          onClick={() => setMainMode('synthesizer')}
          className={`px-5 py-2.5 rounded-xl text-xs sm:text-sm font-black transition-all flex items-center gap-2 cursor-pointer ${
            mainMode === 'synthesizer'
              ? 'bg-blue-600 text-white shadow-3d-blue scale-[1.02]'
              : 'text-slate-600 hover:text-slate-900 hover:bg-white/80'
          }`}
        >
          <BookOpen className="w-4 h-4" />
          <span>AI Study Suites & Synthesizer</span>
        </button>

        <button
          onClick={() => setMainMode('chat')}
          className={`px-5 py-2.5 rounded-xl text-xs sm:text-sm font-black transition-all flex items-center gap-2 cursor-pointer ${
            mainMode === 'chat'
              ? 'bg-blue-600 text-white shadow-3d-blue scale-[1.02]'
              : 'text-slate-600 hover:text-slate-900 hover:bg-white/80'
          }`}
        >
          <Bot className="w-4 h-4 text-amber-300" />
          <span>AI Chat Tutor & Assistant</span>
          <span className="px-1.5 py-0.5 rounded-md text-[9px] font-black uppercase bg-amber-400 text-slate-950">
            24/7 Live
          </span>
        </button>

        <button
          onClick={() => setMainMode('assignment')}
          className={`px-5 py-2.5 rounded-xl text-xs sm:text-sm font-black transition-all flex items-center gap-2 cursor-pointer ${
            mainMode === 'assignment'
              ? 'bg-blue-600 text-white shadow-3d-blue scale-[1.02]'
              : 'text-slate-600 hover:text-slate-900 hover:bg-white/80'
          }`}
        >
          <FileCheck className="w-4 h-4 text-emerald-400" />
          <span>AI Assignment Solver</span>
        </button>
      </div>

      {/* MODE 1: AI Chat Assistant & Tutor */}
      {mainMode === 'chat' && (
        <AIChatView />
      )}

      {/* MODE 2: AI Assignment Solver */}
      {mainMode === 'assignment' && (
        <AssignmentSolverView
          assignments={assignments}
          onAddAssignment={onAddAssignment}
        />
      )}

      {/* MODE 3: Study Suites & Synthesizer */}
      {mainMode === 'synthesizer' && (
        <>
          {/* Top Action Header */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-6 rounded-3xl bg-white/90 backdrop-blur-xl border border-white/90 shadow-3d-sm card-3d">
            <div>
              <div className="flex items-center gap-2">
                <BookOpen className="w-6 h-6 text-blue-600" />
                <h1 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight">AI Study Hub & Document Synthesizer</h1>
              </div>
              <p className="text-xs text-slate-500 mt-1 font-medium">
                Turn raw lectures, PDFs & syllabus notes into complete flashcards, quizzes & 7-day revision plans.
              </p>
            </div>

            <button
              onClick={() => setShowUploader(!showUploader)}
              className="px-5 py-2.5 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white font-black text-xs sm:text-sm shadow-md btn-3d-blue flex items-center gap-2 transition-all cursor-pointer"
            >
              <Upload className="w-4 h-4" />
              {showUploader ? 'Close Uploader' : '+ New Study Suite'}
            </button>
          </div>

      {/* Uploader Box Modal/Expandable */}
      {showUploader && (
        <div className="p-6 sm:p-8 rounded-3xl bg-slate-50 border border-blue-200 shadow-lg space-y-4">
          <div className="flex items-center gap-2">
            <Zap className="w-5 h-5 text-blue-600 animate-pulse" />
            <h2 className="text-lg font-bold text-slate-900">Upload & Synthesize Study Material</h2>
          </div>

          <form onSubmit={handleGenerate} className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Document / Topic Title</label>
                <input
                  type="text"
                  required
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="e.g. Operating Systems: Memory Management & Paging"
                  className="w-full px-3.5 py-2.5 text-xs sm:text-sm rounded-xl bg-white border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Subject</label>
                <input
                  type="text"
                  required
                  value={subject}
                  onChange={(e) => setSubject(e.target.value)}
                  placeholder="e.g. Operating Systems"
                  className="w-full px-3.5 py-2.5 text-xs sm:text-sm rounded-xl bg-white border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Paste Lecture Text, Syllabus, PDF Extract or Topic Description
              </label>
              <textarea
                rows={5}
                required
                value={contentText}
                onChange={(e) => setContentText(e.target.value)}
                placeholder="Paste your lecture transcript, slide content, textbook chapter or syllabus text here..."
                className="w-full p-3 text-xs sm:text-sm rounded-xl bg-white border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-bold text-xs sm:text-sm shadow-md shadow-blue-600/20 flex items-center justify-center gap-2 transition-all"
            >
              {loading ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  <span>AI is generating flashcards, quizzes & notes...</span>
                </>
              ) : (
                <>
                  <Zap className="w-4 h-4" />
                  <span>Generate AI Study Suite</span>
                </>
              )}
            </button>
          </form>
        </div>
      )}

      {/* Main Suite Content Viewer */}
      {selectedSuite ? (
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Library Sidebar List (1 Col) */}
          <div className="lg:col-span-1 space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 px-1">My Notes & Libraries</h3>
            <div className="space-y-2 max-h-[600px] overflow-y-auto pr-1">
              {studySuites.map((s) => (
                <div
                  key={s.id}
                  onClick={() => {
                    setSelectedSuite(s);
                    setCurrentFCIndex(0);
                    setFcFlipped(false);
                    setQuizSubmitted(false);
                  }}
                  className={`p-3.5 rounded-2xl border transition-all cursor-pointer flex items-center justify-between group ${
                    selectedSuite.id === s.id
                      ? 'bg-blue-600 text-white border-blue-600 shadow-md'
                      : 'bg-white text-slate-800 border-slate-200 hover:border-blue-300'
                  }`}
                >
                  <div className="flex-1 pr-2">
                    <span className={`text-[9px] font-bold uppercase px-2 py-0.5 rounded-md ${
                      selectedSuite.id === s.id ? 'bg-white/20 text-white' : 'bg-blue-50 text-blue-600'
                    }`}>
                      {s.subject}
                    </span>
                    <h4 className="font-bold text-xs mt-1.5 line-clamp-1">{s.title}</h4>
                  </div>

                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      onDeleteSuite(s.id);
                      if (selectedSuite.id === s.id) {
                        setSelectedSuite(studySuites.find((item) => item.id !== s.id) || null);
                      }
                    }}
                    className={`p-1.5 rounded-lg transition-colors ${
                      selectedSuite.id === s.id ? 'hover:bg-white/20 text-white' : 'hover:bg-slate-100 text-slate-400'
                    }`}
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              ))}
            </div>
          </div>

          {/* Main Viewer Stage (3 Cols) */}
          <div className="lg:col-span-3 space-y-4">
            {/* Suite Title Bar */}
            <div className="p-5 rounded-3xl bg-white border border-slate-200/80 shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div>
                <span className="text-xs font-bold text-blue-600 uppercase bg-blue-50 px-2.5 py-1 rounded-md border border-blue-100">
                  {selectedSuite.subject}
                </span>
                <h2 className="text-xl font-extrabold text-slate-900 mt-1">{selectedSuite.title}</h2>
              </div>

              <div className="flex items-center gap-2 flex-wrap">
                <button
                  onClick={() => setMainMode('chat')}
                  className="px-4 py-2 rounded-xl bg-indigo-50 hover:bg-indigo-100 text-indigo-700 border border-indigo-200/80 font-black text-xs flex items-center gap-2 transition-all cursor-pointer shadow-2xs"
                >
                  <Bot className="w-4 h-4 text-indigo-600" />
                  Ask AI Tutor About This
                </button>

                <button
                  onClick={handleExportPDF}
                  className="px-4 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold text-xs flex items-center gap-2 transition-colors w-fit cursor-pointer"
                >
                  <Download className="w-4 h-4 text-blue-600" />
                  Export as PDF
                </button>
              </div>
            </div>

            {/* Sub-Tab Navigation Bar */}
            <div className="flex items-center gap-1 bg-slate-100 p-1.5 rounded-2xl overflow-x-auto text-xs font-bold">
              <button
                onClick={() => setActiveTab('notes')}
                className={`px-3.5 py-2 rounded-xl transition-all ${
                  activeTab === 'notes' ? 'bg-white text-blue-600 shadow-xs' : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Notes & Summary
              </button>

              <button
                onClick={() => setActiveTab('flashcards')}
                className={`px-3.5 py-2 rounded-xl transition-all ${
                  activeTab === 'flashcards' ? 'bg-white text-blue-600 shadow-xs' : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Flashcards ({selectedSuite.flashcards.length})
              </button>

              <button
                onClick={() => setActiveTab('quiz')}
                className={`px-3.5 py-2 rounded-xl transition-all ${
                  activeTab === 'quiz' ? 'bg-white text-blue-600 shadow-xs' : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Quiz ({selectedSuite.quiz.length})
              </button>

              <button
                onClick={() => setActiveTab('formulas')}
                className={`px-3.5 py-2 rounded-xl transition-all ${
                  activeTab === 'formulas' ? 'bg-white text-blue-600 shadow-xs' : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Formulas
              </button>

              <button
                onClick={() => setActiveTab('viva')}
                className={`px-3.5 py-2 rounded-xl transition-all ${
                  activeTab === 'viva' ? 'bg-white text-blue-600 shadow-xs' : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Viva Qs
              </button>

              <button
                onClick={() => setActiveTab('revision')}
                className={`px-3.5 py-2 rounded-xl transition-all ${
                  activeTab === 'revision' ? 'bg-white text-blue-600 shadow-xs' : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                7-Day Plan
              </button>
            </div>

            {/* TAB CONTENT 1: Notes & Executive Summary */}
            {activeTab === 'notes' && (
              <div className="space-y-4">
                {/* Executive Summary */}
                <div className="p-5 rounded-2xl bg-blue-50/70 border border-blue-200">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-blue-700 flex items-center gap-1.5 mb-2">
                    <Zap className="w-4 h-4 fill-blue-600" /> Executive Summary
                  </h3>
                  <p className="text-xs sm:text-sm text-slate-800 leading-relaxed">{selectedSuite.summary}</p>
                </div>

                {/* Structured Notes */}
                <div className="p-6 rounded-3xl bg-white border border-slate-200/80 shadow-xs text-xs sm:text-sm text-slate-800 leading-relaxed space-y-3 whitespace-pre-wrap font-sans">
                  <h3 className="text-base font-extrabold text-slate-900 border-b pb-2">Comprehensive Notes</h3>
                  {selectedSuite.fullNotes}
                </div>

                {/* Important Questions */}
                {selectedSuite.importantQuestions?.length > 0 && (
                  <div className="p-6 rounded-3xl bg-white border border-slate-200/80 shadow-xs space-y-3">
                    <h3 className="text-base font-extrabold text-slate-900 border-b pb-2">High-Yield Exam Questions</h3>
                    <div className="space-y-3">
                      {selectedSuite.importantQuestions.map((iq, i) => (
                        <div key={i} className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-1">
                          <div className="flex items-center justify-between">
                            <p className="text-xs font-bold text-slate-900">Q{i+1}. {iq.question}</p>
                            <span className="text-[10px] font-bold px-2 py-0.5 rounded-md bg-white border text-blue-600">
                              {iq.difficulty}
                            </span>
                          </div>
                          <p className="text-xs text-slate-600 pt-1 border-t border-slate-200/60 mt-1">{iq.answer}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* TAB CONTENT 2: Flashcards Deck */}
            {activeTab === 'flashcards' && (
              <div className="p-8 rounded-3xl bg-white border border-slate-200/80 shadow-xs flex flex-col items-center justify-center text-center space-y-6">
                {selectedSuite.flashcards.length > 0 ? (
                  <>
                    <div className="flex items-center justify-between w-full max-w-lg text-xs font-bold text-slate-500">
                      <span>Card {currentFCIndex + 1} of {selectedSuite.flashcards.length}</span>
                      <span>Click to Flip</span>
                    </div>

                    <div
                      onClick={() => setFcFlipped(!fcFlipped)}
                      className={`w-full max-w-lg min-h-[220px] p-8 rounded-3xl border-2 flex items-center justify-center cursor-pointer transition-all duration-300 shadow-md ${
                        fcFlipped
                          ? 'bg-blue-600 text-white border-blue-600 shadow-blue-500/20'
                          : 'bg-slate-50 text-slate-900 border-slate-200 hover:border-blue-400'
                      }`}
                    >
                      <p className="text-base sm:text-xl font-bold leading-relaxed">
                        {fcFlipped
                          ? selectedSuite.flashcards[currentFCIndex].back
                          : selectedSuite.flashcards[currentFCIndex].front}
                      </p>
                    </div>

                    <div className="flex items-center gap-4">
                      <button
                        onClick={() => {
                          setFcFlipped(false);
                          setCurrentFCIndex((prev) => (prev > 0 ? prev - 1 : selectedSuite.flashcards.length - 1));
                        }}
                        className="px-5 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold text-xs"
                      >
                        ← Previous
                      </button>

                      <button
                        onClick={() => {
                          setFcFlipped(false);
                          setCurrentFCIndex((prev) => (prev < selectedSuite.flashcards.length - 1 ? prev + 1 : 0));
                        }}
                        className="px-5 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs"
                      >
                        Next →
                      </button>
                    </div>
                  </>
                ) : (
                  <p className="text-xs text-slate-500">No flashcards available in this suite.</p>
                )}
              </div>
            )}

            {/* TAB CONTENT 3: Interactive Quiz */}
            {activeTab === 'quiz' && (
              <div className="p-6 rounded-3xl bg-white border border-slate-200/80 shadow-xs space-y-6">
                <h3 className="text-base font-extrabold text-slate-900 border-b pb-2">Multiple Choice Quiz</h3>

                <div className="space-y-6">
                  {selectedSuite.quiz.map((q, qIdx) => (
                    <div key={q.id} className="p-5 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-3">
                      <p className="text-sm font-bold text-slate-900">{qIdx + 1}. {q.question}</p>

                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                        {q.options.map((opt, optIdx) => {
                          const isSelected = quizAnswers[q.id] === optIdx;
                          const isCorrect = q.correctAnswer === optIdx;
                          return (
                            <button
                              key={optIdx}
                              disabled={quizSubmitted}
                              onClick={() => setQuizAnswers({ ...quizAnswers, [q.id]: optIdx })}
                              className={`p-3 rounded-xl border text-left text-xs font-medium transition-all ${
                                quizSubmitted
                                  ? isCorrect
                                    ? 'bg-emerald-100 border-emerald-400 text-emerald-900 font-bold'
                                    : isSelected
                                    ? 'bg-red-100 border-red-400 text-red-900 font-bold'
                                    : 'bg-white border-slate-200 opacity-60'
                                  : isSelected
                                  ? 'bg-blue-600 text-white border-blue-600 font-bold'
                                  : 'bg-white border-slate-200 text-slate-800 hover:bg-slate-100'
                              }`}
                            >
                              {opt}
                            </button>
                          );
                        })}
                      </div>

                      {quizSubmitted && (
                        <p className="text-xs font-semibold text-slate-600 pt-2 border-t border-slate-200">
                          <strong>Explanation:</strong> {q.explanation}
                        </p>
                      )}
                    </div>
                  ))}
                </div>

                <div className="flex justify-end pt-4 border-t">
                  <button
                    onClick={() => setQuizSubmitted(true)}
                    className="px-6 py-3 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs shadow-md shadow-blue-600/20"
                  >
                    Submit Quiz & Get Score
                  </button>
                </div>
              </div>
            )}

            {/* TAB CONTENT 4: Formulas */}
            {activeTab === 'formulas' && (
              <div className="p-6 rounded-3xl bg-white border border-slate-200/80 shadow-xs space-y-4">
                <h3 className="text-base font-extrabold text-slate-900 border-b pb-2">Formula & Constants Cheat Sheet</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  {selectedSuite.formulas?.map((f, i) => (
                    <div key={i} className="p-4 rounded-2xl bg-slate-50 border border-slate-200">
                      <p className="text-xs font-bold text-blue-600">{f.name}</p>
                      <p className="text-sm font-mono font-bold text-slate-900 my-1 bg-white p-2 rounded-lg border">
                        {f.formula}
                      </p>
                      <p className="text-xs text-slate-500">{f.description}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* TAB CONTENT 5: Viva Questions */}
            {activeTab === 'viva' && (
              <div className="p-6 rounded-3xl bg-white border border-slate-200/80 shadow-xs space-y-4">
                <h3 className="text-base font-extrabold text-slate-900 border-b pb-2">Oral / Viva Exam Prep</h3>
                <div className="space-y-4">
                  {selectedSuite.vivaQuestions?.map((vq, i) => (
                    <div key={i} className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-2">
                      <p className="text-xs font-bold text-slate-900">Viva Q{i+1}: {vq.question}</p>
                      <p className="text-xs text-slate-700 bg-white p-3 rounded-xl border border-slate-200">
                        <strong>Top-Tier Sample Answer:</strong> {vq.sampleAnswer}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* TAB CONTENT 6: 7-Day Revision Plan */}
            {activeTab === 'revision' && (
              <div className="p-6 rounded-3xl bg-white border border-slate-200/80 shadow-xs space-y-4">
                <h3 className="text-base font-extrabold text-slate-900 border-b pb-2">7-Day Exam Revision Schedule</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  {selectedSuite.revisionPlan?.map((rp, i) => (
                    <div key={i} className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-2">
                      <span className="text-[10px] font-bold uppercase bg-blue-100 text-blue-700 px-2 py-0.5 rounded-md">
                        Day {rp.day}
                      </span>
                      <p className="text-xs font-bold text-slate-900">{rp.topic}</p>
                      <ul className="list-disc list-inside text-[11px] text-slate-600 space-y-1">
                        {rp.tasks?.map((t, ti) => (
                          <li key={ti}>{t}</li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      ) : null}
        </>
      )}
    </div>
  );
};
