import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export async function exportCanvasToPDF(elementId: string, filename: string = 'Resume.pdf'): Promise<void> {
  const elem = document.getElementById(elementId);
  if (!elem) {
    throw new Error(`Element with id #${elementId} not found`);
  }

  // Generate crisp canvas rendering
  const canvas = await html2canvas(elem, {
    scale: 2, // 2x scale for high DPI crisp text
    useCORS: true,
    logging: false,
    backgroundColor: '#ffffff',
    onclone: (clonedDoc) => {
      const clonedElem = clonedDoc.getElementById(elementId);
      if (clonedElem) {
        clonedElem.style.transform = 'none';
        clonedElem.style.boxShadow = 'none';
        clonedElem.style.margin = '0';
        clonedElem.style.width = '100%';
        clonedElem.style.maxWidth = '100%';
        clonedElem.style.borderRadius = '0';
      }
    }
  });

  const imgData = canvas.toDataURL('image/png', 1.0);
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pdfWidth = pdf.internal.pageSize.getWidth(); // 210 mm
  const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

  pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight, undefined, 'FAST');
  pdf.save(filename);
}

export function exportTextToPDF(title: string, content: string, filename: string = 'document.pdf') {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const maxLineWidth = pageWidth - margin * 2;

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(37, 99, 235); // CampusOS Blue (#2563EB)
  doc.text(title, margin, 20);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated by CampusOS AI - ${new Date().toLocaleDateString()}`, margin, 27);

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, 31, pageWidth - margin, 31);

  // Content
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);

  const lines = doc.splitTextToSize(content, maxLineWidth);
  let cursorY = 38;

  for (let i = 0; i < lines.length; i++) {
    if (cursorY > pageHeight - margin) {
      doc.addPage();
      cursorY = 20;
    }
    doc.text(lines[i], margin, cursorY);
    cursorY += 6;
  }

  doc.save(filename);
}

export function exportResumeToPDF(resume: any, filename: string = 'Resume_CampusOS.pdf') {
  const doc = new jsPDF();
  const margin = 15;
  const pageWidth = doc.internal.pageSize.getWidth();
  let cursorY = 20;

  // Name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42);
  doc.text(resume.fullName || 'Student Name', margin, cursorY);
  cursorY += 8;

  // Contact Line
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  const contactText = `${resume.email} | ${resume.phone} | ${resume.location} | ${resume.linkedin}`;
  doc.text(contactText, margin, cursorY);
  cursorY += 8;

  // Line
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.8);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 8;

  // Summary
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(37, 99, 235);
  doc.text('PROFESSIONAL SUMMARY', margin, cursorY);
  cursorY += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);
  const summaryLines = doc.splitTextToSize(resume.summary, pageWidth - margin * 2);
  doc.text(summaryLines, margin, cursorY);
  cursorY += summaryLines.length * 5 + 6;

  // Education
  if (resume.education?.length) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(37, 99, 235);
    doc.text('EDUCATION', margin, cursorY);
    cursorY += 6;

    resume.education.forEach((edu: any) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      doc.text(edu.institution, margin, cursorY);
      doc.text(edu.year, pageWidth - margin - 25, cursorY);
      cursorY += 5;

      doc.setFont('helvetica', 'italic');
      doc.setTextColor(71, 85, 105);
      doc.text(`${edu.degree} - GPA: ${edu.gpa}`, margin, cursorY);
      cursorY += 7;
    });
  }

  // Experience
  if (resume.experience?.length) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(37, 99, 235);
    doc.text('EXPERIENCE', margin, cursorY);
    cursorY += 6;

    resume.experience.forEach((exp: any) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      doc.text(`${exp.role} - ${exp.company}`, margin, cursorY);
      doc.text(exp.duration, pageWidth - margin - 30, cursorY);
      cursorY += 5;

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(51, 65, 85);
      exp.bulletPoints.forEach((bullet: string) => {
        const bulletLines = doc.splitTextToSize(`• ${bullet}`, pageWidth - margin * 2 - 5);
        doc.text(bulletLines, margin + 3, cursorY);
        cursorY += bulletLines.length * 5;
      });
      cursorY += 3;
    });
  }

  // Projects
  if (resume.projects?.length) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(37, 99, 235);
    doc.text('KEY PROJECTS', margin, cursorY);
    cursorY += 6;

    resume.projects.forEach((proj: any) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      doc.text(proj.name, margin, cursorY);
      cursorY += 5;

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(51, 65, 85);
      const descLines = doc.splitTextToSize(proj.description, pageWidth - margin * 2);
      doc.text(descLines, margin, cursorY);
      cursorY += descLines.length * 5;

      doc.setFont('helvetica', 'italic');
      doc.setTextColor(100, 116, 139);
      doc.text(`Tech Stack: ${proj.techStack.join(', ')}`, margin, cursorY);
      cursorY += 7;
    });
  }

  doc.save(filename);
}
